### ISSUE TITLE
Native python object as return crashes node

### ISSUE THREAD

**Issue by s2hc-johan** [esl/Pyrlang#10]
If you create a function that returns a object that is not parable into erlang terms, the node crashes.

An example, create module tdf.py:
```python
def to_die_for(cant_handle_empty_args_yet=None):
    import datetime
    return datetime.datetime.now()
```
start everything up and from erlang call:
```erlang
rpc:call('py@127.0.0.1', 'tdf', 'to_die_for', [<<"foo">>]).
```

node dies with ``RecursionError`` maximum depth

**Comment by kvakvs** [comment]
I think i had this covered, but i will review it.

**Comment by kvakvs** [comment]
Datetime is a recursive object which refers to another datetime (field `max`) which refers... and so on. The only reasonable way would be to detect these loops, or not feed it with recursive objects.

`(atom'datetime', {atom'hour': 0, atom'microsecond': 0, atom'year': 1, atom'day': 1, atom'month': 1, atom'minute': 0, atom'second': 0, atom'tzinfo': None, atom'min': datetime.datetime(1, 1, 1, 0, 0), atom'resolution': datetime.timedelta(0, 0, 1), atom'max': datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)})`

Note the last one (field `max`) which is also a datetime, and it also has field `max` etc

**Comment by s2hc-johan** [comment]
Wouldn't it be enough to convert the more standard object types, in builtin module. Like

* int
* float
* list
* tuple
* dict
* bytes
* string
* whatever standard object I've missed

There is already limitation in conversion between string list and erlang binary  and list.

I have some code that keeps context on python side and you can reference them wen calling functions later on. I've made some hacks to make it work with the current Pyrlang, but that could give us an idea of how to move forward.

**Comment by kvakvs** [comment]
That sort of works.

But some types don't match Erlang. Example: Binary can be bytes or bits (bytes with last byte incomplete). Or list can be a normal list or an improper list (ending with something non-NIL). For this I have binary and list class wrappers, and they are optional (you pass flags to decoder), i think i have set simple decoding to be the default.

I can solve this by ignoring duplicate/recursive objects.

**Comment by kvakvs** [comment]
I have added cycle detection you can try now.

Also empty parameter lists should work.
