### ISSUE TITLE
Support Erlang/OTP 20

### ISSUE THREAD

**Issue by heri16** [esl/Pyrlang#11]
Seems to be getting this error:

`Connection attempt to node '' aborted since it cannot handle ["UTF8_ATOMS"]`

Related: http://erlang.org/pipermail/erlang-questions/2017-July/092785.html

**Comment by heri16** [comment]
Same error in issue #7

**Comment by kvakvs** [comment]
The library was created around May, and R20 was released in June. Will fix soon.

**Comment by heri16** [comment]
This has been fixed?

**Comment by kvakvs** [comment]
It can connect and runs with both R19 and R20
I need more feedback if something goes wrong, and probably must make some tests :)
