### ISSUE TITLE
Python 2 is not working due to presence of Python 3 type hints

### ISSUE THREAD

**Issue by kvakvs** [esl/Pyrlang#12]
Need to devise a clever way to retain python3 type hints and make it compatible with python2.

**Comment by kxepal** [comment]
You can use [`# type: `](https://www.python.org/dev/peps/pep-0484/#compatibility-with-other-uses-of-function-annotations) magic comments. They are recognized as type hints as well. Or use stub `pyi` instead, but they adds quite a lot of overhead to maintenance.

But much better decision is to finally drop 2.x. It's almost 2018 year around.

**Comment by kvakvs** [comment]
It was a request from @s2hc-johan to help him migrate legacy Python2 stuff. Probably he can relax this requirement and we can eventually migrate to asyncio.

**Comment by s2hc-johan** [comment]
Yea, I've actually checked the legacy code and it seems like we'll be able to lift that code to python3 without that much hassel. That is probably better time spent, than making Pyrlang python2.

As far as asyncio we're also waiting for the interface to settle.

**Comment by kvakvs** [comment]
Python 2 is not a goal at all, i'll be closing this
