### ISSUE TITLE
Elixir-friendly docs?

### ISSUE THREAD

**Issue by vegabook** [esl/Pyrlang#19]
I'd be happy to help contribute nicely comprehensive Elixir-friendly documentation. Personally believe https://github.com/esl/Pyrlang/issues/13 and https://github.com/esl/Pyrlang/issues/18 would need to be addressed first however. Think Elixir users will find Pyrlang extremely useful for integrating Python's scientific / data science capabilities.

**Comment by kvakvs** [comment]
This is more like a comment not an issue.
Taking a look at #13 and #18 now and closing this.
Elixir related contributions are welcome.
