### ISSUE TITLE
Docs do not explain how to send a message from Python to a non-named Erlang/Elixir process

### ISSUE THREAD

**Issue by vegabook** [esl/Pyrlang#25]
http://pyrlang.readthedocs.io/en/latest/getting_started.html#send-from-python-to-a-remote

In the above documentation, it is clear how to send a message from a Pyrlang process back to Erlang or Elixir if the process in Erlang/Elixir is already named (example shows with names "shell"). But it is not clear how to format on the Python side if one wants to send to a regular pid such as #PID<0.264.0>.

Does one send "#PID<0.264.0>" as a string? Does one use 264 as an integer? Is there a pid constructor in Pyrlang? Nobody knows. 

I am happy to update the docs myself but first I would need to know how the above is done.

**Comment by vegabook** [comment]
Actually I have figured out how to do this if I first send the pid from the Erlang side, because then I get a Pyrlang.Pid object on the other side. But it might still be useful to know how to construct a Pyrlang.pid object from scratch.

**Comment by OvermindDL1** [comment]
> But it might still be useful to know how to construct a Pyrlang.pid object from scratch.

You generally can't construct PID's from interface, because you wouldn't know what PID to construct because if you have that information then you could just send the PID itself then?

**Comment by vegabook** [comment]
well the problem I had was PID is sent over and converted to string by the call I make to third party software (bloomberg), and I wanted to reconstruct PID from string. What I have done instead is to save a dict of string -> PID so I'm okay. I will close the issue. I still think it's worth putting something in documentation about how to handle this use case, ie: if it is non-named process on erlang side then you should either name it, or communicate it to python side.
