### ISSUE TITLE
Simplified flow for python calls

### ISSUE THREAD

**Issue by s2hc-johan** [esl/Pyrlang#29]
A more pythonistic way of calling functions/objects then MFA is needed. Also when the result of a call is something that can't/shoudn't be sent back to erlang, we need some way of keeping state on the python side and be able to use it later on.

first a calling scheme that fits python world better is 

```erlang
py:call(Node, ObjectPath, Args, KeyWordArgs)
```

To be able to handle results that we want to be able to use in later calls on python side, but don't want sent over the wire, we need some context on python side

```erlang
Ctx = py:new_context(Node),
py:call(Ctx, ObjectPath, Arguments, KeywordArguments),
```

a full example:

```erlang
test() ->
  Ctx = py:new_context('py@127.0.0.1'),
  DT = py:call(Ctx, <<"__import__">>, [<<"datetime">>], #{}),
  Now1 = py:call(Ctx, [DT, <<"datetime.now">>], [], #{}),
  Now2 = py:call(Ctx, [DT, datetime, <<"now">>], [], #{}),
  Res =  py:call(Ctx, [Now2, '__sub__'], [Now1], #{}),
  py:call(Ctx, [Res, <<"total_seconds">>], [], #{}).
```

Discussion
---
In python everything is an object. Some object make sense in converting to types that can be sent 
back to erlang and some don't. The ones that doesn't make sense should just send back a reference, 
that can be used in future calls. 

However sometimes you might have data, for example a huge list, that you're not interested in having 
in erlang, you want to do more processing on it before returning it. Therefore we need some way of 
controlling if a reference or the actual data is sent back to erlang.

**Comment by kvakvs** [comment]
- [ ] Create context
- [ ] Call and immediate call (no history)
- [ ] Indexed variables in call args, and call context
- [ ] Destroy context
