### ISSUE TITLE
setuptools

### ISSUE THREAD

**Issue by s2hc-johan** [esl/Pyrlang#6]
We should implement setuptools to help with an easy installation.

Also we should make sure it works directly for python 2 and 3.

- Dependencies
- Python 2 support
- Python 3 support
- Wheels (also C extensions for major dists?), or maybe python only fallback

**Comment by vegabook** [comment]
so how does one install it without setuptools?

**Comment by vegabook** [comment]
So do we just copy the Pyrlang director to the dist-packages directory?

**Comment by kxepal** [comment]
@vegabook Extremely bad idea.
Good idea: contribute `setup.py` (:

**Comment by vegabook** [comment]
I'd be happy to take a stab, but it would be the first time I've done this. Am a little concerned about the fact that Python 2 doesn't seem to work, https://github.com/esl/Pyrlang/issues/12, so should we still do Python 2 support?

**Comment by s2hc-johan** [comment]
I almost got something working. Can try and commit something soonish. I think I'm the reason for the py2 compatibility, but to be honest I think we're quite far from having this work properly in py2 so it's probably better time spent to move my legacy project to py3 instead of moving pyrlang to py2

**Comment by vegabook** [comment]
Can confirm that this setup.py seems to work fine with Python 3.6 as well. I have the RPC test working.

**Comment by kvakvs** [comment]
Merged #14, i assume this will do for now? :)
