### ISSUE TITLE
Elixir support

### ISSUE THREAD

**Issue by ShalokShalom** [esl/Pyrlang#7]
The documentation seems to suggest, that only Erlang is supported, while Elixir, LFE and so and are for sure also?

**Comment by heri16** [comment]
Elixir has built-in support for Erlang Module Function Arguments calling. However, adding a nice library to wrap erlang boiler code might be nice for some use cases. Don't seem to have much boiler code in Pyrlang, so I would suggest just using it directly from Elixir.

**Comment by heri16** [comment]
I spoke too early.

Seems that Pyrlang will need a patch in the ETF handling.

```python
Dist protocol error: Handshake bad status: b'snot_allowed' (state recv_status)
Protocol requested to disconnect the socket
```

```elixir
Connection attempt from node :"py@127.0.0.1" rejected since it cannot handle ['UTF8_ATOMS'].**
```

**Comment by kvakvs** [comment]
Pyrlang needs some use cases and more feedback to mature. It is a new library which I haven't been using much myself but I expected that @s2hc-johan is/will be using it.

I will fix R20 compatibility soon though.

**Comment by kvakvs** [comment]
Elixir library is not planned for Pyrlang. I updated it to support R19 and R20 though, so you should be good to begin.

Closing this.
