### ISSUE TITLE
RPC call without arguments not handled correct

### ISSUE THREAD

**Issue by s2hc-johan** [esl/Pyrlang#9]
When doing an rpc call without arguments like
```erlang
rpc:call('py@127.0.0.1', 'Pyrlang.logger', 'tty', []).
```

The ``args`` variable in ``GenIncomingCall`` is a ``list``. If you call with any argument it's a ``Pyrlang.term.List``. in gen.py [row 71](https://github.com/esl/Pyrlang/blob/master/Pyrlang/gen.py#L71)
the code assumes it to be a ``Pyrlang.term.List`` causing an exception.

One way would be to check type here and return accordinlgy, but it's probably better to ensure that it's always a ``Pyrlang.term.List``, even when it's empty.

**Comment by kvakvs** [comment]
Happened when simple lists were enabled in decoder (producing Python lists) and they do not have `elements_` field which is used by `term.List`.
Looks like it is solved.
